Feature/ab2 d 5044 metrics lambda support
CMSgov/AB2D-Libs pull request #104
Opened 2022-09-12 14:54 UTC by sb-keane

**JIRA Tickets:**

[AB2D-5044](https://jira.cms.gov/browse/AB2D-5044) - Description

Create a lambda that's called whenever cloudwatch detects a problem with ab2d api worker and their access to supporting services such as efs and the db. 

### What Does This PR Do?

Adds a new lambda that will be invoked whenever cloudwatch healthchecks fail. 

### What Should Reviewers Watch For?

Incompatibilities with cloudwatch.

### Usage/Deployment Instructions

Run gradle buildZip
Go into aws dashboard
Upload the generated zip

### Impacted External Components

### Database Changes

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [X] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [X] Code checked for PHI/PII exposure

2022-09-12 16:15 UTC, sharshar-sb requested changes

2022-09-12 16:15 UTC, sharshar-sb commented on ab2d-events-client/src/main/java/gov/cms/ab2d/eventclient/events/MetricsEvent.java
> +    @Override
Is there no descriptive field telling what the event means?

2022-09-12 16:15 UTC, sharshar-sb commented on build.gradle
> +    eventClientVersion='1.3.1-metrics'
I would increment this to 1.4. It has code changes. No reason to put text.

2022-09-12 16:52 UTC, sb-dkniesteadt approved these changes
Appoved assuming lailas requests will be done

2022-09-21 17:07 UTC, sharshar-sb approved these changes

2022-09-21 18:31 UTC, sb-dkniesteadt approved these changes

2022-09-21 18:36 UTC, merged