Feature/ab2d 4748 event libs
CMSgov/AB2D-Libs pull request #72
Opened 2022-06-17 16:44 UTC by sb-dkniesteadt

**JIRA Tickets:**

[AB2D-4748](https://jira.cms.gov/browse/AB2D-4748) - Create ab2d-libs module to send data to event sqs.

### What Does This PR Do?
Adds event libs for services to use

### What Should Reviewers Watch For?
Any uneeded/needed code i missed

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [x] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [x] Code checked for PHI/PII exposure

2022-06-17 18:31 UTC, sharshar-sb approved these changes

2022-06-21 15:33 UTC, nflearl requested changes
Minor, easily fixed nits.

2022-06-21 15:33 UTC, nflearl commented on ab2d-events-libs/src/test/java/gov/cms/ab2d/eventlibs/utils/Ab2dEnvironmentTest.java
> +package gov.cms.ab2d.eventlibs.utils;
Put in a config package.

2022-06-21 15:33 UTC, nflearl commented on ab2d-events-libs/src/main/java/gov/cms/ab2d/eventlibs/utils/UtilMethods.java
> +public final class UtilMethods {
Please move to where these methods are actually needed.

2022-06-21 15:51 UTC, nflearl approved these changes

2022-06-21 21:15 UTC, merged