Feature/ab2 d 4829 event service integration
CMSgov/AB2D-Libs pull request #86
Opened 2022-07-11 21:40 UTC by sb-dkniesteadt

**JIRA Tickets:**

[AB2D-4829](https://jira.cms.gov/browse/AB2D-4829) - Changes The message being grabbed and sent to sqs, One that is more valuable and can be used for multiple logging types/

### What Does This PR Do?
Change messages object that the sqs liseaner and sender uses

### What Should Reviewers Watch For?
What might break. Or whats a better way of doing this.

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [ ] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [ ] Code checked for PHI/PII exposure

2022-07-11 21:49 UTC, sharshar-sb commented on ab2d-events-client/src/test/java/gov/cms/ab2d/eventclient/config/SendSqsEventTest.java
> +        when(amazonSQSMock.sendMessage(any(SendMessageRequest.class))).thenThrow(new UnsupportedOperationException("I am a failure"));
Such negative talk.

2022-07-11 21:50 UTC, sharshar-sb requested changes

2022-07-11 21:50 UTC, sharshar-sb commented on build.gradle
> +    eventClientVersion='1.1.1'
We're only doing minor versions for the services so this is 1.2.

2022-07-11 21:51 UTC, sb-dkniesteadt commented on ab2d-events-client/src/test/java/gov/cms/ab2d/eventclient/config/SendSqsEventTest.java
> +        when(amazonSQSMock.sendMessage(any(SendMessageRequest.class))).thenThrow(new UnsupportedOperationException("I am a failure"));
Well it is.

2022-07-11 21:56 UTC, sharshar-sb approved these changes

2022-07-11 22:00 UTC, sb-keane commented on build.gradle
> +    // AB2D libraries
Is this duplicated intentionally?

2022-07-11 22:09 UTC, sb-dkniesteadt commented on build.gradle
> +    // AB2D libraries
nope, good catch

2022-07-11 22:36 UTC, sb-keane approved these changes

2022-07-12 15:06 UTC, sharshar-sb approved these changes

2022-07-12 15:16 UTC, merged